# Generated by Django 2.1.2 on 2019-01-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20190114_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='top_bid_account_id',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
