# Generated by Django 2.1.2 on 2019-01-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_book_top_bid_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='account',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='book',
        ),
    ]
