# Generated by Django 2.1.2 on 2019-01-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20190117_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
    ]
